# Generated by Django 2.1.2 on 2018-10-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TiposDocumentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(blank=True, default='', max_length=100)),
                ('codigo', models.CharField(blank=True, default='', max_length=1)),
                ('codigo_banplus', models.CharField(blank=True, default='', max_length=3)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
