# Generated by Django 2.1.2 on 2018-10-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_proveedores_tiposproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='tiposProveedor',
            field=models.ManyToManyField(db_table='tipos_proveedor_por_proveedor', to='api.TiposProveedor'),
        ),
    ]
