# Generated by Django 2.1.2 on 2018-10-24 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181024_0138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TiposDocumentos',
            new_name='TiposDocumento',
        ),
    ]
