# Generated by Django 2.1.2 on 2018-10-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181024_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('estatus', models.CharField(blank=True, default='', max_length=1)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.RemoveField(
            model_name='proveedores',
            name='tiposProveedor',
        ),
        migrations.RenameModel(
            old_name='TiposProveedor',
            new_name='TiposCliente',
        ),
        migrations.DeleteModel(
            name='Proveedores',
        ),
        migrations.AddField(
            model_name='clientes',
            name='tiposCliente',
            field=models.ManyToManyField(db_table='api_tiposcliente_cliente', to='api.TiposCliente'),
        ),
    ]
