# Generated by Django 2.1.2 on 2018-10-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181025_2227'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tiposcliente',
            table='api_tipos_cliente',
        ),
    ]
