# Generated by Django 2.1.2 on 2018-11-13 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_estatus'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tiposdocumento',
            table='api_tipos_documento',
        ),
    ]
