# Generated by Django 2.1.2 on 2018-11-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181113_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposMoneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(blank=True, default='', max_length=100)),
                ('simbolo', models.CharField(blank=True, default='', max_length=1)),
            ],
            options={
                'db_table': 'api_tipos_moneda',
                'ordering': ('created',),
            },
        ),
    ]
